-- MySQL Script generated by MySQL Workbench
-- Thu Aug 15 22:54:15 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema rest_demo
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema rest_demo
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `rest_demo` DEFAULT CHARACTER SET utf8 ;
USE `rest_demo` ;

-- -----------------------------------------------------
-- Table `rest_demo`.`classes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rest_demo`.`classes` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rest_demo`.`student`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rest_demo`.`student` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `address` VARCHAR(45) NOT NULL,
  `classes_id` BIGINT(20) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_student_classes_idx` (`classes_id` ASC) VISIBLE,
  CONSTRAINT `fk_student_classes`
    FOREIGN KEY (`classes_id`)
    REFERENCES `rest_demo`.`classes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

INSERT INTO CLASSES(name) VALUES('ITSOL-INTERN-1');
INSERT INTO CLASSES(name) VALUES('ITSOL-INTERN-2');
INSERT INTO CLASSES(name) VALUES('ITSOL-INTERN-3');
INSERT INTO CLASSES(name) VALUES('ITSOL-INTERN-4');
INSERT INTO CLASSES(name) VALUES('ITSOL-INTERN-5');

